# Generated by Django 5.2.7 on 2025-11-27 12:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('AcNo', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_postal_code', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'ACCOUNT',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('recordNo', models.AutoField(primary_key=True, serialize=False)),
                ('crop_type', models.CharField(max_length=100)),
                ('disease', models.CharField(max_length=50)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('record_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account_acno', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.account')),
            ],
            options={
                'verbose_name_plural': 'History Records',
                'db_table': 'HISTORY',
            },
        ),
    ]
