# Generated by Django 5.2.7 on 2025-11-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='AcNo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
